### ISSUE TITLE
Undefined index in error parsing

### ISSUE THREAD

**Issue by petaak** [Spoje-NET/php-flexibee#4]
In the commit: https://github.com/Spoje-NET/php-flexibee/commit/7df25e9378342a1bdb28ccdb0994439bda0d273c you've changed the keys used to parse the error messages.
Original key: $responseDecoded['results'][0]['errors']
New key: $responseDecoded['results'][0]['result']

The new key does not correspond with the real response structure so I'm getting the folowing error:
ErrorException: Undefined index: result in /var/www/html/vendor/spojenet/flexibee/src/FlexiPeeHP/FlexiBeeRO.php:1081

Is it an intentional change or a mistake?

**Comment by Vitexus** [comment]
Hallo, there is problem with response to array. Could you please provide your query that produces badly parsed error response ?
Thank you for your help

**Comment by Vitexus** [comment]
Hallo Petr, 
could you please confirm that latest commit fix our issue ?

**Comment by petaak** [comment]
For example when I don't have permission to create an invoice I get the following response:
```
{
   "winstrom":{
      "@version":"1.0",
      "success":"false",
      "stats":{
         "created":"0",
         "updated":"0",
         "deleted":"0",
         "skipped":"0",
         "failed":"1"
      },
      "results":[
         {
            "request-id":"ext:a6d87525-9fc1-4478-9b9b-dd63db1a75d3",
            "errors":[
               {
                  "message":"Nemáte oprávnění na vytvoření záznamu v evidenci Doklady faktur. (Role uživatele: IS) [ext:a6d87525-9fc1-4478-9b9b-dd63db1a75d3]"
               }
            ]
         }
      ]
   }
}
```

**Comment by Vitexus** [comment]
Ok, your problem was hotfixed. See https://github.com/Spoje-NET/php-flexibee/blob/master/src/FlexiPeeHP/FlexiBeeRW.php#L139

We need more complex error response parser in future.
Do you need release or you use dev-maser in your project ?

**Comment by petaak** [comment]
Seems to be working. Thanks for a quick fix. A release would be nice.

**Comment by Vitexus** [comment]
Here we go https://github.com/Spoje-NET/php-flexibee/releases/tag/1.39
Have good night
